### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by tmdoit** [dtube/dtube#89]
macOS Mojave 10.14.
Tested with Chrome,Brave, Safari and Firefox.
![screenshot 2019-02-15 at 21 18 44 2](https://user-images.githubusercontent.com/26081817/52882495-22b29700-3168-11e9-9627-8d5efe68648a.png)

**Comment by GOKOP** [comment]
As far as I know this is because dtube uses third party tool for searching and that tool no longer works. That should be fixed tho, I dodn't understand how such service is practical to use at all without search feature.

**Comment by wehmoen** [comment]
Unfortunately a blockchain has no search function. When Asksteem was shutdown there was no real alternative for DTube. The team is still trying to figure out the best way to handle search requests and video suggestion.

**Comment by kenorb** [comment]
What about embedding DuckDuckGo search results?

E.g. <https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fd.tube%2F+blockchain&t=canonical&ia=web>

**Comment by GOKOP** [comment]
+1, it may not me the perfect idea but it's good enough.

**Comment by josiah14** [comment]
It's been over a season (about 4 months) since this issue was logged, and Search is still broken.  Reddit shows that people are leaving the platform because of this.  Whether the solution is ideal or not, whatever can get things functional again, even for the short term, that should be implemented, or else this platform runs the risk of dying.

**Comment by serpent7776** [comment]
Search still doesn't work and there's no mention on the site about that fact. This just leaves new users coming to the service wondering what's going on.

**Comment by wehmoen** [comment]
Please wait for the next big update.

**Comment by skzap** [comment]
I think it works again now ! Closing issue :)
